package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"
	"go-enter/graph/model"
	"go-enter/internal"
	"strconv"
)

// CreateBook is the resolver for the createBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, input model.NewBook) (*model.Book, error) {
	book, err := r.Srv.CreateBook(ctx, &input)
	if err != nil {
		return nil, err
	}
	return book, nil
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context) ([]*model.Book, error) {
	books, err := r.Srv.GetAllBooks(ctx)
	if err != nil {
			return nil, fmt.Errorf("queryResolver: failed to get all books: %w", err)
	}
	return books, nil
}

// Book is the resolver for the book field.
func (r *queryResolver) Book(ctx context.Context, id string) (*model.Book, error) {
	intID, err := strconv.Atoi(id)
	if err != nil {
		// Handle error during string to int conversion.
		return nil, fmt.Errorf("invalid ID format: %v", err)
	}

	book, err := r.Srv.GetBookByID(ctx, intID)
	if err != nil {
		return nil, err
	}
	return book, nil
}

// Mutation returns internal.MutationResolver implementation.
func (r *Resolver) Mutation() internal.MutationResolver { return &mutationResolver{r} }

// Query returns internal.QueryResolver implementation.
func (r *Resolver) Query() internal.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
